### ISSUE TITLE
Recommendation: Use an ORM

### ISSUE THREAD

**Issue by trishankkarthik** [kcg295/eWitnessServer#1]
I see that [Storage/storage.py](https://github.com/kcg295/eWitnessServer/blob/2fb9664ef7b2d9aa367148e07f95e3446ab19161/Storage/storage.py) uses a lot of hand-written SQL. May I recommend using an [ORM](https://www.fullstackpython.com/object-relational-mappers-orms.html) instead?

Using an ORM has a few advantages:

1. Usually simpler to read and write than SQL.
2. Easier migration of SQL (using migration tools such as [Alembic](https://pypi.python.org/pypi/alembic)).
3. Less prone to security bugs such as SQL injection (especially given user input).

It has a few disadvantages:

1. Some queries may actually be harder to write using an ORM rather than hand-written SQL. A good ORM would let you write raw SQL if you have to.
2. Learning curve, depending on the library.

**Comment by trishankkarthik** [comment]
SQLAlchemy

**Comment by kcg295** [comment]
started fixing this is commit 692fe41613ff60666acdaa643084e9ddbeb56441. Will be testing shortly.
